# Generated by Django 2.2 on 2021-01-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('conversion_based', models.CharField(blank=True, max_length=10)),
                ('conversion', models.IntegerField()),
            ],
        ),
    ]
