# Generated by Django 2.2 on 2020-12-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('cooking_serving', models.IntegerField()),
                ('cooking_time', models.TimeField(blank=True)),
            ],
        ),
    ]
