# Generated by Django 2.2 on 2021-01-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_auto_20210101_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='price',
            field=models.IntegerField(default=''),
            preserve_default=False,
        ),
    ]
