# Generated by Django 2.2 on 2021-01-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_remove_recipe_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
