# Generated by Django 2.2 on 2021-01-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0010_remove_recipe_recipe_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_price',
            field=models.IntegerField(default=0),
        ),
    ]
