# Generated by Django 2.2 on 2021-01-12 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0011_recipe_recipe_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_price',
        ),
    ]
