# Generated by Django 2.2 on 2021-01-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0012_remove_recipe_recipe_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_price',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
