# Generated by Django 2.2 on 2021-01-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0013_recipe_recipe_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_price',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
