# Generated by Django 2.2 on 2021-02-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0014_auto_20210112_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_name',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
