# Generated by Django 2.2 on 2021-03-19 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0005_remove_order_total'),
        ('order_delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDeliveryJoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_delivery.OrderDelivery')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
            ],
        ),
    ]
