# Generated by Django 2.2 on 2021-03-20 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0012_auto_20210315_1534'),
        ('order_delivery_integration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdeliveryjoin',
            name='order',
        ),
        migrations.AddField(
            model_name='orderdeliveryjoin',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='user_profile.UserProfile'),
            preserve_default=False,
        ),
    ]
