# Generated by Django 2.2 on 2020-12-24 09:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_date', models.DateTimeField(default=datetime.datetime(2020, 12, 24, 15, 21, 36, 134627))),
                ('modfied_date', models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 24, 15, 21, 36, 134627))),
                ('name', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('unit_of_measure', models.CharField(blank=True, choices=[('gram', 'g'), ('kilogram', 'kg'), ('mililiter', 'ml'), ('liter', 'l')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
