# Generated by Django 2.2 on 2020-12-24 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredients',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='ingredients',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='ingredients',
            name='modfied_date',
        ),
        migrations.RemoveField(
            model_name='ingredients',
            name='password',
        ),
    ]
