# Generated by Django 2.2 on 2020-12-24 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0002_auto_20201224_1539'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredients',
            new_name='Ingredient',
        ),
    ]
