# Generated by Django 2.2 on 2021-01-12 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0003_auto_20201224_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='unit_of_measure',
        ),
    ]
