# Generated by Django 2.2 on 2021-02-08 13:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_auto_20210103_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='contact_number',
            field=models.IntegerField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 8, 18, 59, 31, 470412)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='modfied_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 8, 18, 59, 31, 470412)),
        ),
    ]
