# Generated by Django 2.2 on 2021-03-15 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0011_auto_20210315_0055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='modfied_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='password',
        ),
    ]
