# Generated by Django 2.2 on 2021-03-10 13:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20210310_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 10, 19, 2, 0, 969623)),
        ),
        migrations.AlterField(
            model_name='user',
            name='modfied_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 10, 19, 2, 0, 969623)),
        ),
    ]
