# Generated by Django 2.2 on 2021-03-25 09:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20210317_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_delivery_person',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 14, 59, 16, 490795)),
        ),
        migrations.AlterField(
            model_name='user',
            name='modfied_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 25, 14, 59, 16, 490795)),
        ),
    ]
