# Generated by Django 2.2 on 2021-01-01 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_ingredient', '0002_unitofmeasure'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='unit_converter',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='recipe_ingredient.UnitOfMeasure'),
            preserve_default=False,
        ),
    ]
