# Generated by Django 2.2 on 2021-01-12 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_ingredient', '0004_recipeingredient_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredient',
            name='unit_of_measure',
        ),
    ]
