# Generated by Django 2.2 on 2021-01-30 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_ingredient', '0005_remove_recipeingredient_unit_of_measure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredient',
            name='price',
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit_converter',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='unit_of_measure.UnitOfMeasure'),
        ),
        migrations.DeleteModel(
            name='UnitOfMeasure',
        ),
    ]
