# Generated by Django 2.2 on 2021-03-16 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210316_0045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='delivered',
        ),
    ]
